package LMDS_ICD;
//
// ******* Auto-Generated Code - DO NOT Modify !! ********
//
public class EnDef {
    public enum host_name_ce{
        HOST_UNKNOWN,
        HOST_ATE_SERVER,
        HOST_MPU,
        HOST_PCM,
        HOST_JPM,
        HOST_JPM2,
        HOST_LUMO,
        HOST_FUZE1_PRXY,
        HOST_GPS_UBLOX_PRXY,
        HOST_GPS_SAASM_PRXY,
        HOST_GPS_MPU_PRXY,
        HOST_ALTITUDE_MPU_PRXY,
        HOST_AHRS_PRXY,
        HOST_CAMERA_PRXY,
        HOST_LAN_PRXY,
        HOST_FUZE2_PRXY,
        HOST_OPM_PRXY,
        HOST_JPM_USB1,
        HOST_JPM_USB2
    };
    public enum process_name_ce{
        PR_UNKNOWN,
        PR_TST_CMND,
        PR_PERDC,
        PR_ATE_TF1,
        PR_ATE_TF2,
        PR_ATE_TF3,
        PR_ATE_TF4,
        PR_PRXY
    };
    public enum msg_code_ce{
        MSG_CODE_UNKNOWN,
        MSG_CODE_DS_CNTRL,
        MSG_CODE_CMND_RSPNS,
        MSG_CODE_EO_CNTRL,
        MSG_CODE_EO_STTS,
        MSG_CODE_VDO_ENC_CNTRL,
        MSG_CODE_VDO_ENC_STTS,
        MSG_CODE_PRPLSN_CNTRL,
        MSG_CODE_PRPLSN_STTS,
        MSG_CODE_INT_COMM_TST_RSLTS,
        MSG_CODE_PWR_MSRMNT,
        MSG_CODE_AIR_DATA,
        MSG_CODE_VDO_FPS,
        MSG_CODE_SER_COMM_TST,
        MSG_CODE_INT_SER_COMM_TST,
        MSG_CODE_TEMP_MSRMNTS,
        MSG_CODE_PWM_CNTRL_STTS,
        MSG_CODE_DSCRT_CNTRL,
        MSG_CODE_DSCRT_STTS,
        MSG_CODE_SET_VDO_ANNOT,
        MSG_CODE_TX_FUZE,
        MSG_CODE_RX_FUZE,
        MSG_CODE_TX_GPS_UBLOX,
        MSG_CODE_RX_GPS_UBLOX,
        MSG_CODE_TX_SAASM,
        MSG_CODE_RX_SAASM,
        MSG_CODE_TEXT,
        MSG_CODE_TX_AHRS,
        MSG_CODE_RX_AHRS,
        MSG_CODE_BATTERY_STTS,
        MSG_CODE_TX_GPS_MPU,
        MSG_CODE_RX_GPS_MPU,
        MSG_CODE_TX_JPM_TL,
        MSG_CODE_RX_JPM_TL,
        MSG_CODE_TX_JPM_CONTROL,
        MSG_CODE_RX_JPM_CONTROL,
        MSG_CODE_TX_CAMERA,
        MSG_CODE_RX_CAMERA,
        MSG_CODE_TX_MCM,
        MSG_CODE_RX_MCM,
        MSG_CODE_WRITE_GET_CNFG_PARAM,
        MSG_CODE_READ_CNFG_PARAM,
        MSG_CODE_SAVE_ALL_CNFG_PARAMS,
        MSG_CODE_GET_DS_REVSN
    };
    public enum lmds_state_ce{
        LMDS_ST_UNKNOWN,
        LMDS_ST_IDLE,
        LMDS_ST_SINGLE_UUT,
        LMDS_ST_AV_ASSY,
        LMDS_ST_INTEGRATED_LM,
        LMDS_ST_LUMO_LP_NOGPS,
        LMDS_ST_LUMO_LP_GPS_UBLOX,
        LMDS_ST_LUMO_LP_GPS_SAASM
    };
    public enum camera_mode_ce{
        camera_mode_unknown,
        camera_mode_rate,
        camera_mode_pilot_window,
        camera_mode_stow,
        camera_mode_park
    };
    public enum spectrum_ce{
        spectrum_unknown,
        spectrum_visible,
        spectrum_IR
    };
    public enum IR_Polarity_ce{
        IR_Polarity_unknown,
        IR_Polarity_hot_white,
        IR_Polarity_hot_black
    };
    public enum Serviceability_ce{
        Serviceability_unknown,
        Serviceability_GO,
        Serviceability_NOGO,
        Serviceability_DEGRADED
    };
    public enum Motor_state_ce{
        Motor_state_unknown,
        Motor_state_off,
        Motor_state_on
    };
    public enum GPS_Fix_Type_ce{
        Fix_Type_unknown,
        No_Fix,
        Dead_Reckoning_only,
        D2_Fix,
        D3_Fix,
        GNSS_dead_reckoning_combined,
        Time_only_fix
    };
    public enum dscrt_id_ce{
        DSCRT_UNKNOWN,
        LUMO_DSCRT_IN_DIP_SW_0,
        LUMO_DSCRT_IN_DIP_SW_1,
        LUMO_DSCRT_IN_DIP_SW_2,
        LUMO_DSCRT_IN_UMBILICAL_INIT,
        LUMO_DSCRT_IN_NG_ESAD_STATUS,
        LUMO_DSCRT_OUT_NG_ESAD_TF1,
        LUMO_DSCRT_OUT_NG_ESAD_TF2,
        LUMO_DSCRT_OUT_NG_ESAD_CMND_TRIG,
        LUMO_DSCRT_OUT_NG_ESAD_EN5V,
        LUMO_DSCRT_OUT_SAASM_EN5V,
        LUMO_DSCRT_OUT_SAASM_GPS_PRGRM,
        LUMO_DSCRT_OUT_SAASM_UART_FNCTN,
        LUMO_DSCRT_OUT_SAASM_RST,
        LUMO_DSCRT_OUT_SAASM_KDP_PRGRM,
        LUMO_DSCRT_OUT_SAASM_ZROIS,
        LUMO_DSCRT_OUT_LD_GR,
        LUMO_DSCRT_OUT_LD_RD,
        LUMO_DSCRT_OUT_ESAD_LGC_PWR,
        LUMO_DSCRT_OUT_URT2_PHY,
        MPU_DSCRT_IN_MCU_HW_RST,
        MPU_DSCRT_IN_MPU_GPS_1PPS,
        MPU_DSCRT_IN_DISC_IN4_CON,
        MPU_DSCRT_IN_DISC_IN5_CON,
        MPU_DSCRT_IN_JPM_FORCE_OFF_OUT_3V3,
        MPU_DSCRT_OUT_MCU_DSP_RST,
        MPU_DSCRT_OUT_LED_GREEN,
        MPU_DSCRT_OUT_LED_RED,
        MPU_DSCRT_OUT_MCU_HW_RST_INHIBIT,
        MPU_DSCRT_OUT_HW_PWR_SW1,
        MPU_DSCRT_OUT_VPU_GP1,
        MPU_DSCRT_OUT_VPU_GP2,
        MPU_DSCRT_OUT_VPU_GP3,
        MPU_DSCRT_OUT_VPU_GP4,
        MPU_DSCRT_OUT_DISC_OUT1_CON,
        MPU_DSCRT_OUT_DISC_OUT2_CON,
        MPU_DSCRT_OUT_DISC_OUT3_CON,
        MPU_DSCRT_OUT_JPM_PWR_DIS,
        PCM_DSCRT_IN_ACK_FIRE,
        PCM_DSCRT_IN_LAUNCH_MICRO_SW,
        PCM_DSCRT_IN_ACK_8_2_OK,
        PCM_DSCRT_IN_PAT_PB,
        PCM_DSCRT_IN_LAUNCH_RS,
        PCM_DSCRT_IN_LAUNCH_PB,
        PCM_DSCRT_IN_SW_BIT_OK,
        PCM_DSCRT_IN_CPLD_DONE,
        PCM_DSCRT_IN_CUT_OFF,
        PCM_DSCRT_OUT_GGC_FIRE,
        PCM_DSCRT_OUT_LED_RED_BAT,
        PCM_DSCRT_OUT_LED_GREEN,
        PCM_DSCRT_OUT_SW_BIT_OK,
        PCM_DSCRT_OUT_RST_CPLD,
        JPM_DSCRT_OUT_JPM_FORCE_OFF_OUT_3V3,
        JPM_DSCRT_IN_MCU_HW_RST_INHIBIT,
        JPM_DSCRT_IN_VPU_GP1,
        JPM_DSCRT_IN_VPU_GP2,
        JPM_DSCRT_IN_VPU_GP3,
        JPM_DSCRT_IN_VPU_GP4,
        JPM_DSCRT_OUT_GPIO07,
        JPM_DSCRT_OUT_GPIO09,
        JPM_DSCRT_IN_GPIO11,
        JPM_DSCRT_IN_GPIO12,
        LUMO_DSCRT_OUT_PITOT_HTNG_CNTRL,
        PCM_DSCRT_IN_UAV_LAUNCHED,
        MPU_DSCRT_OUT_JETSON_PWR_ON_OFF,
        MPU_DSCRT_OUT_CAMERA_ON_OFF,
        MPU_DSCRT_OUT_MIPI_RSTN,
        MPU_DSCRT_OUT_FAN_ON_OFF
    };
    public enum PWM_channel_id_ce{
        PWM_UNKNOWN,
        LUMO_PWM_PRCHUT,
        RESERVED_1,
        RESERVED_2,
        MPU_PWM_OUT1,
        MPU_PWM_OUT2,
        MPU_PWM_OUT3,
        MPU_PWM_OUT4,
        MPU_PWM_OUT5,
        MPU_PWM_OUT6,
        PCM_PWM_OUT1,
        PCM_PWM_OUT2,
        PCM_PWM_OUT3,
        PCM_PWM_OUT4,
        PCM_PWM_LAUNCH_SERVO
    };
    public enum UUT_cmnd_rspns_ce{
        UUT_CMND_RSPNS__UNKNOWN,
        UUT_CMND_RSPNS_OK,
        UUT_CMND_RSPNS_RJCT
    };
    public enum dscrt_val_ce{
        DSCRT_VAL_LOW,
        DSCRT_VAL_HIGH,
        DSCRT_VAL_UNKNOWN
    };
    public enum video_annotations_pattern_ce{
        video_annotations_pattern_unknown,
        video_annotations_pattern_A,
        video_annotations_pattern_B,
        video_annotations_pattern_C,
        video_annotations_pattern_D
    };
    public enum temp_snsor_ce{
        TEMP_SNSOR_UNKNOWN,
        LUMO_TEMP_ONBRD,
        LUMO_TEMP_EXT,
        LUMO_TEMP_1WIR,
        MPU_TEMP_ONBRD,
        PCM_TEMP_ONBRD1,
        PCM_TEMP_ONBRD2,
        PCM_TEMP_EXT,
        JPM_TEMP_ONBRD0,
        JPM_TEMP_ONBRD1,
        JPM_TEMP_ONBRD2,
        JPM_TEMP_ONBRD3
    };
    public enum pwr_sgnal_ce{
        PWR_SGNAL_UNKNOWN,
        LUMO_12_V_DC_MAIN,
        LUMO_12_V_DC_ESAD_LGC,
        LUMO_3_3_V_DC,
        LUMO_5_V_DC,
        LUMO_5_5_V_DC,
        MPU_1V2_DC,
        MPU_1V8_DC,
        MPU_2V5_DC,
        MPU_5V_DC,
        MPU_8V2_DC,
        MPU_12V_DC,
        PCM_5V_DC,
        PCM_12V_DC,
        PCM_8_2V_DC,
        PCM_BAT_V_DC
    };
    public enum config_params_ce{
        CP_UNKNOWN,
        CP_LUMO_PITOT_GN_OFST,
        CP_LUMO_ALT_GN_OFST,
        CP_LUMO_PARA_CLS_OPN_RLS_PWM,
        CP_LUMO_AV_FUZE_COMB,
        CP_LUMO_CMRA_BORSIT_OFST,
        CP_MPU_TAIL_OFST,
        CP_MPU_AILRN_OFST
    };
}
